### ISSUE TITLE
Create based webpage for ToDo to link with application

### ISSUE THREAD

**Issue by batman084** [batman084/Overflow#3]
- [ ] Research HTML templates
- [ ] Research color palettes
- [ ] Coordinate with team about appearance
- [ ] Refer back to original menu page
- [ ] Draw rough draft in Paint
- [ ] Code it all
